<?php
/**
 * Entry point "recaptcha" script registration and enqueue.
 *
 * This file will be copied to the assets output directory
 * with Webpack using wp-scripts build. The build command must
 * be run before this file will be available.
 *
 * This file must be included from the build output directory in a project
 * and will be loaded from there.
 *
 * @package courier
 */

/**
 * Register the recaptcha entry point assets so that they can be enqueued.
 */
function courier_register_recaptcha_scripts(): void {
	/**
	 * Asset file generated by wp-scripts.
	 *
	 * @var array{dependencies: string[], version: string}|false $asset_file
	 */
	$asset_file = include __DIR__ . '/index.asset.php';

	if ( ! $asset_file ) {
		return;
	}

	wp_register_script(
		'courier-recaptcha-js',
		plugins_url( 'index.js', __FILE__ ),
		$asset_file['dependencies'],
		$asset_file['version'],
		true
	);
}
add_action( 'init', 'courier_register_recaptcha_scripts' );
